package ie.gmit.sw;

/**
 * 
 * @author Andrej Lavrinovic - G00196948
 * 
 * Number generator that generate big number, which representing request.
 * Each request will be identified by this number
 *
 */
public class JobNumberGenerator implements Numberable {

	// field
	private long jobNumber;

	// getters and setters generated by eclipse
	/* (non-Javadoc)
	 * @see ie.gmit.sw.Numberable#getJobNumber()
	 */
	
	@Override
	public long getJobNumber() {
		return jobNumber;
	}
	
	// number generator
	/* (non-Javadoc)
	 * @see ie.gmit.sw.Numberable#generateNumber()
	 */
	@Override
	public void generateNumber(){
		this.jobNumber = (long)(Math.random() * 1000000000 + 1);
		System.out.println("JobNumberGenerator: " + this.jobNumber);
	}
}
