package ie.gmit.sw;

/**
 * 
 * @author Andrej Lavrinovic - G00196984
 * 
 * Mumberable is generated by eclipse.
 * Used for Implement JobNumberGenerator that generates number
 * for Request identifier.
 *
 */
public interface Numberable {

	// getters and setters generated by eclipse
	public long getJobNumber();

	// number generator
	public void generateNumber();

}