package ie.gmit.sw;

/**
 * 
 * @author Andrej Lavrinovic - G00196984
 * 
 * Request class represents container for carrying data that must
 * be used by comparator to compare and return result
 *
 */

public class Request implements Requestable {

	// Object fields that represents request data
	private String stringOne;
	private String stringTwo;
	private String algorithm;
	private String jobNumber;
	
	private Integer result;
	
	// Constructor section generated by eclipse
	public Request(String stringOne, String stringTwo, String algorithm, String jobNumber) {
		super();
		this.stringOne = stringOne;
		this.stringTwo = stringTwo;
		this.algorithm = algorithm;
		this.jobNumber = jobNumber;
		
		this.result = null;
		
	}
	
	// get/set -ers generated by eclipse using Source -> generate Getters and Setters
	/* (non-Javadoc)
	 * @see ie.gmit.sw.Requestable#getStringOne()
	 */
	@Override
	public String getStringOne() {
		return stringOne;
	}
	/* (non-Javadoc)
	 * @see ie.gmit.sw.Requestable#setStringOne(java.lang.String)
	 */
	@Override
	public void setStringOne(String stringOne) {
		this.stringOne = stringOne;
	}
	/* (non-Javadoc)
	 * @see ie.gmit.sw.Requestable#getStringTwo()
	 */
	@Override
	public String getStringTwo() {
		return stringTwo;
	}
	/* (non-Javadoc)
	 * @see ie.gmit.sw.Requestable#setStringTwo(java.lang.String)
	 */
	@Override
	public void setStringTwo(String stringTwo) {
		this.stringTwo = stringTwo;
	}
	/* (non-Javadoc)
	 * @see ie.gmit.sw.Requestable#getAlgorithm()
	 */
	@Override
	public String getAlgorithm() {
		return algorithm;
	}
	/* (non-Javadoc)
	 * @see ie.gmit.sw.Requestable#setAlgorithm(java.lang.String)
	 */
	@Override
	public void setAlgorithm(String algorithm) {
		this.algorithm = algorithm;
	}
	/* (non-Javadoc)
	 * @see ie.gmit.sw.Requestable#getJobNumber()
	 */
	@Override
	public String getJobNumber() {
		return jobNumber;
	}
	/* (non-Javadoc)
	 * @see ie.gmit.sw.Requestable#setJobNumber(long)
	 */
	@Override
	public void setJobNumber(String jobNumber) {
		this.jobNumber = jobNumber;
	}

	/*
	 * (non-Javadoc)
	 * @see ie.gmit.sw.Requestable#getResult()
	 */
	@Override
	public Integer getResult() {
		return result;
	}

	/*
	 * (non-Javadoc)
	 * @see ie.gmit.sw.Requestable#setResult(int)
	 */
	@Override
	public void setResult(int result) {
		this.result = result;
	}
	
}
