package ie.gmit.sw;

/**
 * 
 * @author Andrej Lavrinovic - G00196984
 * 
 * Requestable interface is generated by eclipse from Request class
 *
 */

public interface Requestable {

	// get/set -ers generated by eclipse using Source -> generate Getters and Setters
	String getStringOne();

	void setStringOne(String stringOne);

	String getStringTwo();

	void setStringTwo(String stringTwo);

	String getAlgorithm();

	void setAlgorithm(String algorithm);

	String getJobNumber();

	void setJobNumber(String jobNumber);

	Integer getResult();

	void setResult(int result);
}