package ie.gmit.sw;

/**
 * 
 * @author Andrej Lavrinovic - G00196984
 * 
 * Resultable interface is generated by eclipse from Result class
 *
 */

public interface Resultable {

	// get/set -ers generated by eclipse using Source -> generate Getters and Setters
	String getStringOne();

	void setStringOne(String stringOne);

	String getStringTwo();

	void setStringTwo(String stringTwo);

	String getAlgorithm();

	void setAlgorithm(String algorithm);

	long getJobNumber();

	void setJobNumber(long jobNumber);

}